version: 2
jobs:
  build:
    working_directory: ~/liver-fhir
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: cra build
          command: |
            CI="" yarn build

      - persist_to_workspace:
          root: ~/liver-fhir
          paths:
            - build

  deploy:
    working_directory: ~/liver-fhir
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout:
          path: ~/liver-fhir

      - attach_workspace:
          at: ~/liver-fhir

      - run:
          name: auth1
          command: echo $KEY_FILE | base64 -d > key.json

      - run:
          name: auth2
          command: gcloud auth activate-service-account --key-file=key.json --project=$PROJECT

      - run:
          name: deploy
          command: |
            gsutil rsync -r build gs://physicalexamination.neilashford.com

workflows:
  version: 2
  deploy-the-thing:
    jobs:
      - build
      - deploy:
          requires:
            - build
